### ISSUE TITLE
2.0 Camera

### ISSUE THREAD

**Issue by Alex20cm** [Siterizer/new-world-fishing-bot#242]
2.0 is working perfectly the only problem is that when is catching a rare fish and shows the animation most of the time won't reset back, sometimes is working sometimes isn't . but i ll say every 30 minutes the bot will stop working as it will not fish anymore as the camera will be facing left side. 

Is it possible to edit the amount of they the b button is pressed? or something?

**Comment by calmeep** [comment]
Just resetting it back to normal then setting free camera move back to b?
@phGH

**Comment by Admalll** [comment]
same problem for me, didnt find the solution

**Comment by dvz95** [comment]
Yep. I have just recently getting this issue like a few days ago. I’m still on version 1.2.1. Sometimes camera is to the left or slightly down.

**Comment by syntax001** [comment]
Sometimes this is caused by an in game bug where the freecam just doesn't work. That is fixed by resetting to default keybindings and changing it back to 'b'. however that bug only happens between closing and opening the game, not during a playsession. 

ALWAYS before you start the bot, check that the freecam is working. If its working, and the bot still fails to reset the camera reliably, then its possibly something to do with the bot.

**Comment by snozzberry91** [comment]
Same issue for me. I've tried resetting the default keys and then changing it back to B. It didn't fix the problem. 
Sometimes it will run for 30mins+ without the camera staying in the position after catching and uncommon+ and sometimes it will do it after a few catches.

**Comment by Alex20cm** [comment]
Yes, i can confirm that the problem persists, i make sure 3 times that the camera is working and still getting the camera on the left side.

**Comment by Admalll** [comment]
i just cant find the way its not bugging. Every 30 minutes camera goes on :(

**Comment by idimo** [comment]
same problem

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
